postgresql:
  password:
    postgres: password
  config:
    listen_addresses: '*'
  pg_hba:
    -
      type: 'host'
      db:   'all'
      user: 'all'
      addr: '0.0.0.0/0'
      method: 'md5'
    -
      type: 'host'
      db:   'all'
      user: 'all'
      addr: '::1/0'
      method: 'md5'

mysql:
  data_dir: "/vagrant/mysql"
  allow_remote_root: true
  initial_root_password: "password"

solrcloud:
  zk_run: true
